services:
  crm-agent:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: crm-agent
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app
    depends_on:
      - firebase-emulator
  firebase-emulator:
    image: node:18-slim
    container_name: firebase-emulator
    working_dir: /home/firebase
    volumes:
      - ./firebase:/home/firebase
    command: >
      sh -c "npm install -g firebase-tools &&
            firebase emulators:start --only firestore --project fake-project --host 0.0.0.0"
    ports:
      - "4000:4000" # Emulator UI
      - "8080:8080" # Firestore
